### ISSUE TITLE
Vtipná létající plošina v lvl 1

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#14]
**Čeho se týká**
Vtipná létací plošina. Nic víc, nic míň
![98EBF8C0-08C4-4DDC-B242-73D9D6D3F419](https://user-images.githubusercontent.com/55358457/67436880-ca357280-f5ef-11e9-955d-b51fbb99fa10.png)

**Comment by Hruza** [comment]
Odstraněno
