### ISSUE TITLE
Možnost pauznutí hry

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#15]
**Co to bude?**
Při použití klávesy Esc se zastaví hra

**Jak by to mělo fungovat?**
Hráč má možnost zastavit hru a v mezičase si například dojít udělat čaj, zdokumentovat bug nebo si prohlížet zarámované obrazy profesorů poblíž obrazovky bez rizika usmrcení ve hře.

**Jak by to případně mělo vypadat?**
Asi by stačila reakce na použití tlačítka Esc.

**Comment by Hruza** [comment]
V nové verzi
