### ISSUE TITLE
[BUG] (Lze přenášet armor mezi různými save)

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#16]
**Čeho se týká**
Přechodů mezi různými uloženými saves

**Co se děje?**
Hraju-li level na SAVE1 a používám ARMOR1 a ukončím li level a a zapnu SAVE2 a chci-li spustit level, mám automaticky nastavený ARMOR1, který nevlastním na tomto save.
Pokud hru s tímto ARMOR1 spustím, hra tento armor pochopitelně nenačte a hráč je (pravděpodobně) bez brnění (ověřeno na hostivař suit)

**Screenshot**

![2880FDAE-7A44-4537-BC09-F0ED54893736](https://user-images.githubusercontent.com/55358457/67510028-83e61f00-f694-11e9-86fb-e2fd7bf22459.jpeg)

**Další**
Tento bug se vztahuje pouze na brnění, na zbraně se nevztahuje.

**Comment by Hruza** [comment]
Opraveno v nové verzi
