### ISSUE TITLE
[BUG] (posouvadlo)

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#17]
**Čeho se týká**
Menu, vybírání předmětů 

**Co se děje?**
Posuvný ukazatel u zbraní a zbrojí je závislý na save s nejvyšším počtem daných předmětů. 
Jinými slovy u většiny savů se ukazatel dá posouvat, i když by neměl.

**Screenshot**
![CE8EBC35-0289-4341-A71F-72638EC9F04D](https://user-images.githubusercontent.com/55358457/67626127-72914400-f847-11e9-8bb9-e085771fcee1.jpeg)

**Další**
Jedná se sice o drobnost, ale občas se save načte s posunutým ukazatelem a hráč nevidí žádné předměty.

**Comment by Hruza** [comment]
To by mělo být opraveno

**Comment by fifa000001** [comment]
Vypadá to tak
