### ISSUE TITLE
[BUG] (CORRUPT SAVE IN THE MIDDLE GLITCH)

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#18]
**Čeho se týká**
Schématu ukládání a obecně práce s uloženými soubory

**Co se děje?**
Chyba umožňuje používat předměty z profilu A na profilu B

**Pojem poškozený save**
Chyba využívá existence poškozeného uloženého profilu ve hře. Tento profil se dá vytvořit kupříkladu tím, že vytvoříme obyčejný profil a potom z příslušného úložného souboru s koncovkou dat vymažeme veškerý text. Poškozený save poznáme podle toho, že při spuštění hry u něj nebude napsáno žádné jméno. Dále označujme tento poškozený save jako C.

**Popis**
Glitch se vytvoří následovně:

1) Spustíme hru a spustíme Save A
2) Přepneme na poškozený save
3) Spustíme zde první úroveň (Tím, že save je poškozený, je možné zde načíst zbraně ze Save A)
4) Úspěšně dokončíme tuto úroveň. (Další úroveň tu spustit nepůjde, ale to nevadí)
5) Spustíme Save B
6) Máme automaticky předvybrané zbraně ze Save A a můžeme s nimi hrát kolik úrovní chceme

**Další**
Drsný, co? :D 🗡

**Comment by Hruza** [comment]
V nové verzi by se rozbitý save neměl ukazovat ;)
