### ISSUE TITLE
Matematické dělo

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#20]
**Co to bude?**
Nová zbraň

**Jak by to mělo fungovat?**
Střílí velmi silný projektil, který pomalu poletí přímou dráhou cca 5 vteřin, ničí všechno přímou cestou a pak expoduje. Nicméně nabíjení bude trvat značnou dobu.

**Jak by to případně mělo vypadat?**
L hopitalovo dělo vypadá jako dělo, co hrdě nese jméno svého zakladatele. (A možná nějaký matematicky symbol)
Projektem si nejsem jistý. Třeba zlomek nekonecno /nekonecno a nakonec zmizí dělící čára zlomku a nekonečna se rozleti různými smery. Samozřejmě pokud tě napadne lepší "matetický lore", tak jedině dobře :)

**Comment by Hruza** [comment]
V nové verzi
