### ISSUE TITLE
[BUG] (Grafická interakce lim e^x a bonusu)

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#21]
**Čeho se týká**
grafiky

**Co se děje?**
Nekonečno je přerušováno proužky žluté barvy.

**Co by se mělo dít?**
Buď bonus, nebo nekonečno by mělo být na pozadí, ne však mišmaš.

**Screenshot**
![Snímek obrazovky (11)](https://user-images.githubusercontent.com/55358457/68711759-9ae4a680-059a-11ea-9d81-4651e968e707.png)

**Comment by fifa000001** [comment]
Stejný problém je i u ostatních zbraní, například integrálního meče.
![Snímek obrazovky (22)](https://user-images.githubusercontent.com/55358457/68992744-bf2cd580-086f-11ea-9b7e-87ae62f494a1.png)
![Snímek obrazovky (23)](https://user-images.githubusercontent.com/55358457/68992747-cc49c480-086f-11ea-9ba6-d3769ddd5872.png)

**Comment by Hruza** [comment]
Mělo by to být opraveno pro všechny zbraně
