### ISSUE TITLE
[BUG] (Posloupnosti útočí skrz zdi)

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#22]
**Čeho se týká**
Chování nepřátel.

**Co se děje?**
Nepřátele ubírají životy skrz zeď pomocí útoků na blízko

**Screenshot**
![Snímek obrazovky (19)](https://user-images.githubusercontent.com/55358457/68980282-565a4480-0800-11ea-9c8e-59a0864b57bf.png)

**Comment by Hruza** [comment]
Už by neměly (1.3.0)
