### ISSUE TITLE
Wolfram Alfa racket launcher

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#23]
**Co to bude?**
Nová zbraň

**Jak by to mělo fungovat?**
Hráč vystřelí naváděnou raketu na každého nepřítele na obrazovce. Nicméně raketa má omezený dolet a je pochopitelně možné, že nedoletí. Zároveň síla rakety by neměla být příliš silná a tedy by se nemělo jednat o instakill.

**Jak by to případně mělo vypadat?**
Jako rakety. Které letí.

**Comment by Hruza** [comment]
Trochu předěláno, ale vznikl Wolfram alfa v nové verzi

**Comment by fifa000001** [comment]
Jeden Wolfram Alfa je až až.
