### ISSUE TITLE
[BUG] Level Generation - "Out of Bounds"

### ISSUE THREAD

**Issue by Abysswalker11** [Hruza/Dungeons-and-Functions#27]
Lvl vygenerován takovým způsebem, že vedle bariéry bránicí opuštění místnosti se vygeneroval illusory wall umožňující opuštění místnosti bez poražení nepřátel. Exit byl ovšem stále zamčen.
![Tresspassing](https://user-images.githubusercontent.com/58297057/69810870-1d9d7080-11ed-11ea-8670-c7a6c823b655.png)

**Comment by Hruza** [comment]
Tento případ nijak neošetřuji (stejně jako další nechtěně případy). Generování secretů asi ještě upravím.

**Comment by fifa000001** [comment]
Upřímně, ono to většinou ani není na škodu, tím, že místnost stejně potřebuju dokončit.

**Comment by Hruza** [comment]
Opraveno v 1.3 0
