### ISSUE TITLE
[BUG] Weapons - Ranged CD blocks weapon swap

### ISSUE THREAD

**Issue by Abysswalker11** [Hruza/Dungeons-and-Functions#29]
Cooldown, který nastává po použití ranged zbraně, neumožňuje přepnutí na druhou equipped zbraň.

**Comment by Hruza** [comment]
Ano, to je správně, je to hlavně kvůli l'Hospitalovi. Hráč by neměl střílet z druhé zbraně, když se mu první "nabíjí".
