### ISSUE TITLE
[BUG] Infimum - Unlock level

### ISSUE THREAD

**Issue by Abysswalker11** [Hruza/Dungeons-and-Functions#33]
K otevření lvl infimum stačí dokončit libovolný lvl, tedy splěním lvl test je možno úplně přeskočit lvl introductory lecture.

**Comment by Hruza** [comment]
Level Test je level obtížnosti 8, ale zároveň má stejné progres ID jako introductory lecture, jeho dokončení je tedy ekvivalentní dokončení introductory lecture. Jelikož test je jen testovací, není to problém, ale zkusím změnit jeho progress ID.
