### ISSUE TITLE
[BUG] Weapon not sacrificed

### ISSUE THREAD

**Issue by Abysswalker11** [Hruza/Dungeons-and-Functions#37]
Pokud pro upgrade zbraně použiji zbraň, kterou mám equipnutou (v tomto konkrétním případě ve druhém slotu, nutno otestovat zda přetrvává i pro první), tak mi zbraň sice zmizí z inventáře, ale při výběru levelu ji mám stále nasazenou a mohu jí bez omezení používat.

**Comment by Hruza** [comment]
Opraveno v nové verzi
