### ISSUE TITLE
[BUG] Špatně vygenerovaný secret

### ISSUE THREAD

**Issue by Hruza** [Hruza/Dungeons-and-Functions#38]
**Co se děje?**
V některé z pokročilejších úrovni se generuje špatně secret. Celá dlaždice se vyplní žlutým boxem, který není zrovna "secret".

**Comment by Abysswalker11** [comment]
Vypadá to jen na problém difficulty 3 levelu.

**Comment by Abysswalker11** [comment]
*levelů

**Comment by Hruza** [comment]
Opraveno společně s Abel-Dirichletem
