### ISSUE TITLE
[BUG] Gamma funkce nemá být drop

### ISSUE THREAD

**Issue by Hruza** [Hruza/Dungeons-and-Functions#39]
**Co se děje?**
Gamma funkce by neměla být dostupná jako drop, pouze jako vylepšení exponenciály.

**Comment by fifa000001** [comment]
A co tahle? 
![Snímek obrazovky (33)](https://user-images.githubusercontent.com/55358457/92417174-2e5a1a00-f161-11ea-8dae-8f4091d4a7cb.png)
