### ISSUE TITLE
[BUG] Room doors 

### ISSUE THREAD

**Issue by Abysswalker11** [Hruza/Dungeons-and-Functions#44]
During room encounter with at least enemy being sum, the doors blocking acces to corridors will open after all originally spawned enemies were defeated, ignoring any possibly surviving enemies who were spawned by the sum.

**Comment by Hruza** [comment]
Je to tak zamýšlené, měly by dveře čekat na všechny?

**Comment by fifa000001** [comment]
Nejsem si jistý. Obecně herní plán je dost nevyužitý, když nejde utíkat před enemáky do jiných uliček a tady to šlo. Nevadilo mi to.

**Comment by Hruza** [comment]
Nechám to takto, stačí zabít sumu.
