### ISSUE TITLE
[BUG] Level generation problems

### ISSUE THREAD

**Issue by Abysswalker11** [Hruza/Dungeons-and-Functions#46]
The "The Abel-Dirichlet Theorem" level generated with following problems:

1) no functioning minimap, displays only player icon, no corridors or rooms were revealed
2) secret door with nothing behind it
![No_secret](https://user-images.githubusercontent.com/58297057/92362432-49407600-f0f0-11ea-993e-866c7a0168b3.png)
3) after passing through the secret door, player gets out of bounds and can move freely in the black void surrounding the level
    or the outer doesn´t even generates itself and accesing out of bounds state is even easier
![Out_of_bounds](https://user-images.githubusercontent.com/58297057/92362766-c835ae80-f0f0-11ea-9318-312cba58f06e.png)

**Comment by fifa000001** [comment]
Potvrzuji

**Comment by fifa000001** [comment]
Co více, level Abel-Dirichlet je rozbité výrazně více. Nezobrazuje se správně se skore a nelze ho dokončit. Po dosažení exitu si nelze vybrat odměnu a tedy nelze kolo ukončit.
![Snímek obrazovky (31)](https://user-images.githubusercontent.com/55358457/92376769-5a46b280-f103-11ea-83d8-399d9fa96b23.png)

**Comment by Hruza** [comment]
Opraveno v další verzi
