### ISSUE TITLE
[BUG] (Yuki reward(less))

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#51]
**Čeho se týká**
Secret level

**Co se děje?**
Na konci levelu, když se zobrazí "cute machinegun", dialog nelze odklinout a level tedy nelze ukončit

**Screenshot**
![Snímek obrazovky (32)](https://user-images.githubusercontent.com/55358457/92413595-14b0d680-f151-11ea-9e94-c21c06f7a2d6.png)

**Další**
Doporučil bych prodloužit zobrazení textu po zabití Yuki. Bezprostředně po její smrti jde po hráčí typicky banda tuleňů a není občas čas si dotyčný nápis přečíst.

**Comment by Hruza** [comment]
Opraveno v nové verzi

**Comment by fifa000001** [comment]
> Opraveno v nové verzi

HA
