### ISSUE TITLE
Proč zabíjení tuleňů nezvyšuje scóre?

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#53]
Rozumím, že v příslušném levelu je scóre naprosto zbytečné. Nicméně to přináší jisté zadostiučinění, když se scóre zvyšuje a po celém levelu scóre 0 není nic pěkného...

K argumentu, že tuleni jsou milí a za jejich zabíjení by nemělo být scóre, dodám, že milí nejsou a pokusili se mě zabít. Scóre bych si zasloužil.

**Comment by Hruza** [comment]
Ne
