### ISSUE TITLE
Dvojklik jako alternativa k přetahování

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#55]
**Co to bude?**
Zjednodušení začátku levelu.

**Jak by to mělo fungovat?**
V historických verzích verzích D&F bylo možná při spouštění levelu vybrat zbraň pouhým kliknutím. Bylo by možná pro hráče, co jsou líní zbraň přetahovat, přidat možnost dvojkliku, kde zbraň by se automaticky objevila ve slotu?

Přetahování je super, ale bylo by fajn mít další možnost.

**Comment by Hruza** [comment]
Přidáno v nové verzi
