### ISSUE TITLE
[BUG] (Nepříjemné barevné záblesky)

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#56]
**Čeho se týká**
Nepříjemné ostré červené zábleky, zraňující hráčův zrak.

**Kdy se to děje?**
Při nepřerušované střelbě pomocí High School Notes na {b_n} a odvetné palbě.

**Screenshot**
Záblesky jsou extrémně krátké, screenhot je obtížné pořídit.

**Comment by fifa000001** [comment]
Bylo by vhodné otestovat i na jiném počítači, nejedná li se převážně o chybu hardwaru.

**Comment by fifa000001** [comment]
Upřesnění, k zábleskům duchází při kolizi projektilů {b_n} a High School Notes.

**Comment by Hruza** [comment]
Záblesky odstraněny v 1.3.0.2
