### ISSUE TITLE
[BUG] (Špatné zobrazení odměn)

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#57]
**Čeho se týká**
Odměn na konci kola.

**Co se děje?**
V jistých případech se odměny, ze kterých hráč vybírá, nevejdou na obrazovku.

**Screenshot**
![Snímek obrazovky (34)](https://user-images.githubusercontent.com/55358457/92594526-2e623300-f2a3-11ea-9ea2-b3d268d0f16c.png)

**Návrhy na řešení**
Pomohlo by vycentrování odměn, případně omezení počtu odměn, ze kterých hráč bude vybírat.

**Comment by Hruza** [comment]
Opraveno v 1.3.0.2. Odměny by měly být vycentrované.
