### ISSUE TITLE
[BUG] (Console symbol)

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#59]
**Čeho se týká**
Konzole

**Co se děje?**
Při aktivaci konzole se symbol ; případně ` (podle toho, jestli je používána česká nebo anglická klávesnice) napíše do textového pole, které je právě vybráno.

**Co by se mělo dít?**
Tyto symboly by se něměli psát při každém otevření a zavření konzole.

**Screenshot**
![Snímek obrazovky (35)](https://user-images.githubusercontent.com/55358457/92603124-3cb64c00-f2af-11ea-97c9-9b86580bdbbd.png)

**Další**
Je to neestetické a navíc to může komplikovat zadávání příkazů do konzole , protože zavřu-li a otevřu-li konzoli a měl li jsem před tím konzoli vybranou, tak se dané symboly napíší do konzole.

**Comment by Hruza** [comment]
Můžu to vyřešit tím, že konzoli odstraním úplně :)

**Comment by fifa000001** [comment]
> Můžu to vyřešit tím, že konzoli odstraním úplně :)

To bezpochyby můžeš. Ale až ti nepůjde v konzoli spustit příkaz, protože tam bude znak navíc, vzpomeneš si na mě :D

**Comment by Hruza** [comment]
Konzole bude časem předělána, tím by se měl problém vyřešit.
