### ISSUE TITLE
[BUG-possibly] (funkce prostřelí štít)

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#60]
**Co se děje?**
Funkce f je schopná přímo prostřelit štít.

**Screenshot**
![Snímek obrazovky (36)](https://user-images.githubusercontent.com/55358457/92608777-11832b00-f2b6-11ea-9b4e-073f235561e8.png)

**Comment by Hruza** [comment]
Nastavil jsem, aby funkce f prostřelila vše, ale je pravda, že na štít jsem zapomněl (Štít možná bude předělán, tak mu nedávám tolik pozornosti).
Každopádně, je to na tobě: Měl by štít zastavit projektil funkce f?

**Comment by fifa000001** [comment]
Aktuálně je štít docela k ničemu, pravda. Podle mě měl, je větší zábava se ten projektil snažit zastavit tímto způsobem.
Nicméně nejsem jediný hráč téhle hry ...

**Comment by Hruza** [comment]
Opraveno v 1.3.0.2.
