### ISSUE TITLE
[BUG] (Yuki STILL reward(less))

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#61]
Come  on...
It`s still a thing. 

https://github.com/Hruza/Dungeons-and-Functions/issues/51#issue-695355029

![Snímek obrazovky (38)](https://user-images.githubusercontent.com/55358457/92639712-823d3e00-f2dc-11ea-8dc4-18e24c4fec25.png)

**Comment by Hruza** [comment]
Tentokrát už snad opraveno.
