### ISSUE TITLE
[BUG] ??? can´t claim loot

### ISSUE THREAD

**Issue by Abysswalker11** [Hruza/Dungeons-and-Functions#62]
After finishing ??? loot appears but there is no option to collect resulting in soft lock. Tested twicer. Game diffiuclty - Field´s Medal Winner. Presence of the bug in other difficulties have not been tested

**Comment by fifa000001** [comment]
viz https://github.com/Hruza/Dungeons-and-Functions/issues/61

**Comment by Hruza** [comment]
Viz #61
