### ISSUE TITLE
[BUG] (Grafická interakce exitu a High school notes)

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#63]
**Čeho se týká**
Design

**Co se děje?**
Podobně jako v https://github.com/Hruza/Dungeons-and-Functions/issues/21 dochází ke kolizi zbraně a exitu.

**Co by se mělo dít?**
Exit a zbraň by se měli nacházet na různých hladinách, aby nedocházelo ke grafické kolizi.

**Screenshot**
![Snímek obrazovky (41)](https://user-images.githubusercontent.com/55358457/92727389-4f905580-f36f-11ea-8a49-35350ee37fc6.png)

**Comment by Hruza** [comment]
Opraveno v další verzi.
