### ISSUE TITLE
[BUG] (Sedmý save file)

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#64]
**Čeho se týká**
Saves

**Co se děje?**
Hráč se dostane nejvýše k šesti savům.

**Co by se mělo dít?**
Bylo by pěkné umožnit v rámci savů scrollování.

**Screenshot**
![Snímek obrazovky (42)](https://user-images.githubusercontent.com/55358457/93021317-478c1c00-f5e2-11ea-96b9-85bdb35bb614.png)

**Comment by Hruza** [comment]
Opraveno v 1.3.0.2

![image](https://user-images.githubusercontent.com/45245203/93714988-a8799e00-fb66-11ea-9a02-292eaac2df09.png)
