### ISSUE TITLE
[BUG] (Dva upgrady za cenu jednoho)

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#65]
**Čeho se týká**
Upgrade

**Co se děje?**
Je možné při obětování předmětu v průběhu upgradu aplikovat draging na předmět v inventáři. Ačkoliv po upgradu předmět z inventáře zmizí, pokud má hráč stále vybraný, může ho využít v upgradu dalšího předmětu.

**Screenshot**
![Snímek obrazovky (43)](https://user-images.githubusercontent.com/55358457/93022004-a18ee080-f5e6-11ea-8748-f65501ba5e38.png)

**Comment by Hruza** [comment]
Opraveno, v 1.3.0.2 obětovaný item zmizí z inventáře ihned po kliknutí tlačítka upgrade.
