### ISSUE TITLE
[BUG] (The infimum of enemies is...)

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#66]
**Čeho se týká**
Level The infimum

**Co se děje?**
Jednou začas se vygeneruje místonost bez nepřátel, hráč dostane dva body okamžitě, když do ní vstoupí.

**Screenshot**
![Snímek obrazovky (56)](https://user-images.githubusercontent.com/55358457/93025132-b6c23a00-f5fb-11ea-861b-0e012e8e2b40.png)

**Comment by Hruza** [comment]
V 1.3.0.2 by se to mělo stávat méně často.
