### ISSUE TITLE
[BUG] (Číslo verze hry)

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#67]
**Čeho se týká**
Menu

**Co se děje?**
Číslo verze hry uvedené ve hře v levém dolním rohu je CHYBNÉ.

**Co by se mělo dít?**
Číslo verze hry uvedené ve hře v levém dolním rohu by mělo být SPRÁVNÉ.

**Screenshot**
![Snímek obrazovky (57)](https://user-images.githubusercontent.com/55358457/93646262-2b371780-fa06-11ea-863d-df5373ac6e6d.png)

**Comment by Hruza** [comment]
Verze je přesná na 3 čísla, to je dobré. Ale v dalších verzích bude verze snad správně.
