### ISSUE TITLE
[BUG] (Projektily v secret místnosti)

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#68]
**Čeho se týká**
level

**Co se děje?**
Projektily v secret místnostech explodují na místě.

**Screenshot**
![Snímek obrazovky (59)](https://user-images.githubusercontent.com/55358457/93648048-1a88a080-fa0a-11ea-8c04-1e4524f30c88.png)

**Comment by Hruza** [comment]
Opraveno v 1.3.0.2
