### ISSUE TITLE
[BUG] (Chyba generátoru)

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#69]
**Čeho se týká**
level

**Co se děje?**
Za secretem se občas nevygeneruje černý blok, což umožňuje hráči opustit mapu.

**Screenshot**
![Snímek obrazovky (62)](https://user-images.githubusercontent.com/55358457/93713457-592e7000-fb5c-11ea-81c8-8d2c2d496249.png)

**Další**
Jedná se o bug relativně vzácný, je obtížné ho zaznamenat. Byl spatřen v levelu Convergence a Deeper limit theorems, zdá se, že na příslušné úrovni mapy nezávisí. 

Bug někdy může poznamenat dva secrety, stejně dobře pouze jeden secret.

Bug byl zaznamenán jak u dolního okraje mapy, tak u horního.

Jak v screenshotu jest patrné, k bugu může dojít i relativně blízko "starting pointu". 

V obou zatím pororovaných případech nicméně k bugu došlo v nejvyšším, či nejnižším místu mapu.

**Comment by Hruza** [comment]
Mělo by být opraveno.
