### ISSUE TITLE
[BUG] (Přiliš rychle odemčený secret)

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#70]
**Čeho se týká**
 level
**Co se děje?**
Po nalezení prvního secretu se odemknul i druhý secret, ačkoliv byl trochu dál.

**Screenshot**
![Snímek obrazovky (65)](https://user-images.githubusercontent.com/55358457/93716394-dca58c80-fb6f-11ea-8e67-d38ce28fac02.png)

**Comment by Hruza** [comment]
Nemyslím si, že je potřeba to řešit (secrety stejně nejsou tak schované). Ber to tak, že jsi měl štěstí.
