### ISSUE TITLE
Lepší rozlišení pro krabice křídy

### ISSUE THREAD

**Issue by fifa000001** [Hruza/Dungeons-and-Functions#73]
**Co to bude?**
viz název příspěvku

**Jak by to případně mělo vypadat?**
Na krabici ve hře je umístěn nápis, nicméně přečtu akorát chalk a to s velkými obtížemi...
Chtěl bych si daný nápis moct přečíst.

![Snímek obrazovky (64)](https://user-images.githubusercontent.com/55358457/93719958-3dd85a80-fb86-11ea-94b8-5d96acf807e8.png)

**Comment by Hruza** [comment]
Pokud je to takový problém, tak nápis z krabice smažu.

**Comment by fifa000001** [comment]
Uznávám, že za problém to nepovažuji. Jen mě zajímalo, nejedná-li se o vývojářský easter egg.
